{
 "title": "Internet Weather Overview",
 "tags": [
  "orb",
  "overview",
  "weather"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "orb_name",
    "label": "Orb Name",
    "query": "from(bucket: \"orb_metrics\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"responsiveness\")\n  |> group(columns: [\"orb_name\"])\n  |> distinct(column: \"orb_name\")\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  { "title": "Responsiveness Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Responsiveness State",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"responsiveness\")\n  |> filter(fn: (r) => r._field == \"latency_avg_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> map(fn: (r) => ({ r with state: if r._value < 50000 then \"Excellent\" else if r._value < 100000 then \"OK\" else \"Poor\" }))\n  |> group(columns: [\"state\"])\n  |> count()\n  |> group()\n  |> pivot(rowKey: [], columnKey: [\"state\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Worst Spike",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"responsiveness\")\n  |> filter(fn: (r) => r._field == \"latency_avg_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> max()"
    }
   ]
  },
  {
   "title": "# of Spikes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"responsiveness\")\n  |> filter(fn: (r) => r._field == \"latency_avg_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> filter(fn: (r) => r._value > 200000)\n  |> count()"
    }
   ]
  },
  {
   "title": "Latency Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"responsiveness\")\n  |> filter(fn: (r) => r._field == \"latency_avg_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> aggregateWindow(every: 15s, fn: mean)"
    }
   ]
  },
  { "title": "Reliability Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Uptime %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"scores\")\n  |> filter(fn: (r) => r._field == \"reliability_score\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> mean()"
    }
   ]
  },
  {
   "title": "Outages Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"scores\")\n  |> filter(fn: (r) => r._field == \"reliability_score\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> filter(fn: (r) => r._value < 100)\n  |> count()"
    }
   ]
  },
  {
   "title": "Longest Outage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"scores\")\n  |> filter(fn: (r) => r._field == \"reliability_score\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> filter(fn: (r) => r._value < 100)\n  |> stateDuration(fn: (r) => true, column: \"duration\", unit: 1m)\n  |> filter(fn: (r) => r.duration > 0)\n  |> max(column: \"duration\")"
    }
   ]
  },
  {
   "title": "Reliability Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"scores\")\n  |> filter(fn: (r) => r._field == \"reliability_score\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Speed Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Speed State",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "maxSpeed = from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"speed_results\")\n  |> filter(fn: (r) => r._field == \"download_kbps\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> max()\n  |> findRecord(fn: (key) => true, idx: 0)\n\nfrom(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"speed_results\")\n  |> filter(fn: (r) => r._field == \"download_kbps\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> map(fn: (r) => ({ r with category: \n      if r._value > maxSpeed._value * 0.8 then \"High\" \n      else if r._value > maxSpeed._value * 0.4 then \"Moderate\" \n      else \"Low\" }))\n  |> group(columns: [\"category\"])\n  |> count()\n  |> group()\n  |> pivot(rowKey: [], columnKey: [\"category\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Peak Download",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"speed_results\")\n  |> filter(fn: (r) => r._field == \"download_kbps\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> max()"
    }
   ]
  },
  {
   "title": "Trough Download",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"speed_results\")\n  |> filter(fn: (r) => r._field == \"download_kbps\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> min()"
    }
   ]
  },
  {
   "title": "Speed Trends",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"speed_results\")\n  |> filter(fn: (r) => r._field == \"download_kbps\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> yield(name: \"Download\")"
    },
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"speed_results\")\n  |> filter(fn: (r) => r._field == \"upload_kbps\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> yield(name: \"Upload\")"
    }
   ]
  },
  { "title": "Web Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "TTFB Breakdown",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"web_responsiveness\")\n  |> filter(fn: (r) => r._field == \"ttfb_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> map(fn: (r) => ({ r with state: if r._value < 200000 then \"Excellent\" else if r._value < 500000 then \"OK\" else \"Poor\" }))\n  |> group(columns: [\"state\"])\n  |> count()\n  |> group()\n  |> pivot(rowKey: [], columnKey: [\"state\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Avg DNS Resolution",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"web_responsiveness\")\n  |> filter(fn: (r) => r._field == \"dns_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> mean()"
    }
   ]
  },
  {
   "title": "Web Trends",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"web_responsiveness\")\n  |> filter(fn: (r) => r._field == \"ttfb_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> aggregateWindow(every: 30s, fn: mean)\n  |> yield(name: \"TTFB\")"
    },
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"web_responsiveness\")\n  |> filter(fn: (r) => r._field == \"dns_us\")\n  |> filter(fn: (r) => r.orb_name == \"${orb_name:pipe}\")\n  |> aggregateWindow(every: 30s, fn: mean)\n  |> yield(name: \"DNS\")"
    }
   ]
  }
 ]
}