{
 "title": "Orb Metrics Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "orbs",
    "query": {
     "query": "select  distinct orb_name from scores where time > now() - interval '1 hour'"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Orb Scores By Orb",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin($__interval, s.time) AS time,\n  s.orb_name,\n  AVG(s.orb_score) AS value\nFROM scores AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1,2\nORDER BY\n  1 ASC, 2ASC"
    }
   ]
  },
  {
   "title": "Lag By Orb",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin($__interval, s.time) AS time,\n  s.orb_name,\n  avg(s.lag_avg_us) AS value\nFROM responsiveness AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1,2\nORDER BY\n  1 ASC,2 ASC"
    }
   ]
  },
  {
   "title": "Worst Orbs by Orb Score",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  s.orb_name,\n  selector_last(s.orb_score, time)['value'] AS orb_score\nFROM scores AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1\nORDER BY\n  2 ASC\nLIMIT 7"
    }
   ]
  },
  {
   "title": "Download Speed By Orb",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin($__interval, s.time) AS time,\n  s.orb_name,\n  AVG(s.download_kbps) AS value\nFROM speed AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1,2\nORDER BY\n  1 ASC, 2ASC"
    }
   ]
  },
  {
   "title": "Upload Speed By Orb",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin($__interval, s.time) AS time,\n  s.orb_name,\n  AVG(s.upload_kbps) AS value\nFROM speed AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1,2\nORDER BY\n  1 ASC, 2ASC"
    }
   ]
  },
  {
   "title": "Scores per Orb",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  s.orb_name,\n  selector_last(s.orb_score, time)['value'] AS orb_score,\n  selector_last(s.reliability_score, time)['value'] AS reliability_score,\n  selector_last(s.responsiveness_score, time)['value'] AS responsiveness_score,\n  selector_last(s.speed_score, time)['value'] AS speed_score\nFROM scores AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1\nORDER BY\n  1 ASC"
    }
   ]
  },
  {
   "title": "TTFB By Orb",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin($__interval, s.time) AS time,\n  s.orb_name,\n  AVG(s.ttfb_us) AS value\nFROM web_responsiveness AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1,2\nORDER BY\n  1 ASC, 2 ASC"
    }
   ]
  },
  {
   "title": "Packet Loss by Orb",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin($__interval, s.time) AS time,\n  s.orb_name,\n  AVG(s.packet_loss_pct) AS value\nFROM responsiveness AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1,2\nORDER BY\n  1 ASC, 2 ASC"
    }
   ]
  },
  {
   "title": "Average Speeds During Period",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  s.orb_name,\n  AVG(s.download_kbps) AS avg_download_kbps,\n  AVG(s.upload_kbps) AS avg_upload_kbps\nFROM speed AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1\nORDER BY\n  1 ASC"
    }
   ]
  },
  {
   "title": "WiFi Metrics",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  s.orb_name,\n  selector_last(network_name, s.time)['value'] as network_name,\n  selector_last(bssid, s.time)['value'] as bssid,\n  AVG(s.rssi_avg) AS rssi_avg,\n  AVG(s.snr_avg) as snr_avg\nFROM wifi_link AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1\nORDER BY\n  1 ASC"
    }
   ]
  },
  {
   "title": "RSSI by Orb",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin($__interval, s.time) AS time,\n  s.orb_name,\n  AVG(s.rssi_avg) AS value\nFROM wifi_link AS s\nWHERE $__timeFilter(s.time)\n  AND regexp_like(s.orb_name, '${orbs:regex}')\nGROUP BY\n  1,2\nORDER BY\n  1 ASC, 2 ASC"
    }
   ]
  }
 ]
}