{
 "title": "Orb Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "orbs",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"orb_metrics\",\n    tag: \"orb_name\",\n    predicate: (r) => true,\n    start: -1h\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mean Scores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "option minWindow = 1m\nfrom(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"scores\" and\n    (r._field == \"orb_score\" or r._field == \"responsiveness_score\" or r._field == \"reliability_score\" or r._field == \"speed_score\") and\n    r.orb_name =~ /^${orbs:regex}$/\n  )\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(\n      every: if int(v: v.windowPeriod) < int(v: minWindow)\n             then minWindow\n             else v.windowPeriod,\n      fn: mean, \n      createEmpty: false\n    )\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Responsiveness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "option minWindow = 15s\n\nfrom(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"responsiveness\" and\n    (r._field == \"lag_avg_us\" or r._field == \"latency_avg_us\") and\n    r.orb_name =~ /^${orbs:regex}$/\n  )\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(\n      every: if int(v: v.windowPeriod) < int(v: minWindow)\n             then minWindow\n             else v.windowPeriod,\n      fn: mean, \n      createEmpty: false\n    )\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"scores\" and\n    (r._field == \"orb_score\" or r._field == \"responsiveness_score\" or r._field == \"reliability_score\" or r._field == \"speed_score\") and\n    r.orb_name =~ /^${orbs:regex}$/\n  )\n  |> drop(columns: [\"_start\", \"_stop\"])\n  |> group(columns: [\"_field\"])\n  |> mean()\n  |> set(key: \"row\", value: \"avg\")\n  |> pivot(rowKey: [\"row\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "option minWindow = 1h\nfrom(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"speed\" and\n    (r._field == \"download_kbps\" or r._field == \"upload_kbps\") and\n    r.orb_name =~ /^${orbs:regex}$/\n  )\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(\n      every: if int(v: v.windowPeriod) < int(v: minWindow)\n             then minWindow\n             else v.windowPeriod,\n      fn: mean, \n      createEmpty: false\n    )\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Web Responsiveness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "option minWindow = 1m\nfrom(bucket: \"orb_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"web_responsiveness\" and\n    (r._field == \"ttfb_us\" or r._field == \"dns_us\") and\n    r.orb_name =~ /^${orbs:regex}$/\n  )\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(\n      every: if int(v: v.windowPeriod) < int(v: minWindow)\n             then minWindow\n             else v.windowPeriod,\n      fn: mean, \n      createEmpty: false\n    )\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}