[[inputs.http]]
  name_override = "wifi_link"
  urls = ["{url}/api/v2/datasets/wifi_link_{interval}.json?id={collector_id}"]
  method = "GET"
  data_format = "json"
  interval = "30s"
  timeout = "10s"

  json_time_key = "timestamp"
  json_time_format = "unix_ms"

  # Treat all these as tags (dimensions)
  tag_keys = [
    "orb_id",
    "orb_name",
    "orb_version",
    "network_name",
    "network_type",
    "network_state",
    "country_code",
    "city",
    "public_ip",
    "private_ip",
    "latitude",
    "longitude",
    "device_name",
    "isp_name",
    "bssid",
    "mac_address"
  ]
