[[outputs.influxdb_v2]]
  urls = ["http://influxdbv3:8181"]
  token = "apiv3_iBaIEEl5YxsL6Q4u1ySV7SixHIGVgOSNhADXQj9EOVAciE9vcnD1XlQf8xqytV9AvxdHvwruxtlhYOW3c_xRMg"
  organization = ""
  bucket = "orb"
  timeout = "10s"
