[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "orb-secret-token"
  organization = "orb"
  bucket = "orb_metrics"
  timeout = "10s"

[[outputs.influxdb_v3]]
  urls = ["http://influxdbv3:8181"]
  token = "apiv3_iBaIEEl5YxsL6Q4u1ySV7SixHIGVgOSNhADXQj9EOVAciE9vcnD1XlQf8xqytV9AvxdHvwruxtlhYOW3c_xRMg"
  database = "orb"
  timeout = "10s"
